name: Docker

on:
  workflow_dispatch:
  push:
    branches: [dev]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  ALIYUN_REGISTRY_CRPI: "${{ secrets.ALIYUN_REGISTRY_CRPI }}"
  ALIYUN_NAME_SPACE_PUBLIC: "${{ secrets.ALIYUN_NAME_SPACE_PUBLIC }}"
  ALIYUN_REGISTRY_USER_ALIYUN: "${{ secrets.ALIYUN_REGISTRY_USER_ALIYUN }}"
  ALIYUN_REGISTRY_PASSWORD_DOCKER: "${{ secrets.ALIYUN_REGISTRY_PASSWORD_DOCKER }}"

jobs:
  build:
    name: Pull and Push Images
    runs-on: ubuntu-latest

    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        df -hT

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        df -hT

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Docker Registry
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        docker login -u $ALIYUN_REGISTRY_USER_ALIYUN -p $ALIYUN_REGISTRY_PASSWORD_DOCKER $ALIYUN_REGISTRY_CRPI

    - name: Process and Push Images
      run: |
        # 数据预处理，判断镜像是否存在
        declare -A duplicate_images
        declare -A temp_map

        # 遍历 images.txt 文件中的每一行
        while IFS= read -r line || [ -n "$line" ]; do
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then continue; fi
            
            # 获取镜像的完整名称，去掉 @sha256 等字符
            image=$(echo "$line" | awk '{print $NF}')
            image="${image%%@*}"

            # 如果镜像名称为空，跳过
            if [ -z "$image" ]; then
                echo "Skipping empty image line"
                continue
            fi

            # 获取镜像名、版本、平台等信息
            image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
            name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
            image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')
            image_tag=$(echo "$image_name_tag" | awk -F':' '{print $2}')
            image_tag="${image_tag:-latest}"

            # 如果镜像名已存在，则标记为重复
            if [[ -n "${temp_map[$image_name]}" ]]; then
                if [[ "${temp_map[$image_name]}" != $name_space  ]]; then
                    duplicate_images[$image_name]="true"
                fi
            else
                temp_map[$image_name]=$name_space
            fi       
        done < images.txt

        # 推送镜像到阿里云不同命名空间
        while IFS= read -r line || [ -n "$line" ]; do
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then continue; fi

            echo "docker pull $line"
            
            # 获取镜像
            image=$(echo "$line" | awk '{print $NF}')
            
            # 确保镜像名不为空
            if [ -z "$image" ]; then
                echo "镜像名称为空，跳过此镜像"
                continue
            fi

            # 使用docker pull获取镜像，确保拉取成功
            docker pull $image || echo "docker pull $image failed" || true

            # 获取平台信息
            platform=$(echo "$line" | awk -F'--platform[ =]' '{if (NF>1) print $2}' | awk '{print $1}')
            platform_prefix=""

            if [ -n "$platform" ]; then
                platform_prefix="${platform//\//_}_"
            fi

            # 获取镜像名、版本等信息
            image_name_tag="${image_name_tag%%@*}"
            new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$platform_prefix$image_name_tag"
            new_image_public="$ALIYUN_REGISTRY_CRPI/$ALIYUN_NAME_SPACE_PUBLIC/$platform_prefix$image_name_tag"

            # 推送镜像
            echo "docker tag $image $new_image"
            docker tag $image $new_image
            docker push $new_image || echo "docker push $new_image failed" || true

            echo "docker tag $image $new_image_public"
            docker tag $image $new_image_public
            docker push $new_image_public || echo "docker push $new_image_public failed" || true

            # 清理镜像
            echo "开始清理磁盘空间"
            df -hT
            docker rmi $image || true
            docker rmi $new_image || true
            docker rmi $new_image_public || true
            echo "磁盘空间清理完毕"
            df -hT
        done < images.txt
